name: hello world

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world message
        run: echo "hello world, Felipe"

      - name: Another task
        run: echo "another task"
    
