name: hello world

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/5 * * * *" # executes every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world message
        run: echo "hello world, Felipe"

      - name: Another task
        run: echo "another task"
    
